### PR TITLE
Adding ColorHelpers.HexadecimalToRgb(string hex) + Tests

### PR DESCRIPTION
**Pull request by hfloyd**
Added a static function to convert a hex code to an RgbColor, which can then be further manipulated. I used this for the code: https://www.programmingalgorithms.com/algorithm/hexadecimal-to-rgb/

### CODE REVIEW

**Comment by abjerner** [comment]
Thanks @hfloyd 👍 

I know this may be due to lack of documentation, but wouldn't the [**Parse**](https://github.com/abjerner/Skybrud.Colors/blob/1a1070fa37d6bbae35573bdb8509aa720c7428bd/src/Skybrud.Colors/ColorHelpers.cs#L286) and [**TryParse**](https://github.com/abjerner/Skybrud.Colors/blob/1a1070fa37d6bbae35573bdb8509aa720c7428bd/src/Skybrud.Colors/ColorHelpers.cs#L303) methods suffice?

The **TryParse** method uses regex, so it may be a bit slower than your proposal, but it covers a few more formats - eg. `hsl(100, 100%, 50%)`.

**Comment by hfloyd** [comment]
Ah, I admit, I didn't see that - or perhaps didn't understand that it was intended for use with hexcodes... I guess some examples would be helpful :-)

Since I didn't see anything explicitly named "Hex...",  I assumed you hadn't included any support for that. Well, you are welcome to include this, even if just because it is obviously discoverable via intellisense, and returns an RGB Color explicitly, but it's up to you, of course.

**Comment by abjerner** [comment]
@hfloyd I had a look at your implementation. While it may only matter on a large scale, `byte.TryParse` seems to be around 3 times faster than `HexadecimalToDecimal`. Could you update the PR to use `byte.TryParse` instead?

If you look at this, could you also have a look at the following:

- **Rename the `HexadecimalToRgb` method to `HexToRgb`**
  I think the shorter name makes more sense, and also matches the `ToHex` methods throughout the package.

- **Move the method to the `ColorUtils` class**
  I haven't really touched the package for a while. Some of my old code may require some cleanup - eg. all the logic from the `ColorHelpers` class should ideally be moved to the `ColorUtils` class instead, so there is only a single class with all the static methods.

- **Perhaps add support for values like `#fff` (with and without the `#`)**
  The `TryParse` method supports the shorter format.

- **Perhaps add support alpha values (with and without the `#`)**
  My own implementation of ´TryParse` doesn't support this, but it probably should.

Are you up for making some or all of these changes? It's okay if you're not - then I'll try to find some time to look at it 😉

**Comment by hfloyd** [comment]
Hi @abjerner I don't mind making the updates. I have some time today ;-) 

I'm not sure about the last request for alpha... I don't think I've seen that used with a hex color code.  If you like, I can move all the "ColorHelpers" into "ColorUtils"... Let me know if that is something you'd like.

**Comment by abjerner** [comment]
> I'm not sure about the last request for alpha... I don't think I've seen that used with a hex color code.

I don't think it's widely used, so feel free to skip that part 😉 

> If you like, I can move all the "ColorHelpers" into "ColorUtils"... Let me know if that is something you'd like.

That would be awesome 👍

**Comment by hfloyd** [comment]
So, looking at the ColorHelpers/ColorUtils... I wonder if it makes sense to determine which is the "main" function for doing each conversion? It seems the others are just returning different types of values - a color object/ints/doubles, etc. I am by no means an expert in color bytes, btw. So I would leave it to you to determine the best method for each type. I can at least take a crack at reorganizing the code.

**Comment by abjerner** [comment]
It's been a while since I wrote most of the code. I think my thoughts where that the methods returning objects would have a small overhead, so there are methods returning int, double or byte as well. I think it should be fine to keep the methods for either approach.

I don't know if that was what you we're describing. Moving the methods to the right class should be the main goal, and then you're welcome to do the cleanup or reorganizing you're comfortable with 😉

**Comment by hfloyd** [comment]
Ok, just reject this PR and take a look at PR #3

**Comment by hfloyd** [comment]
Ps. No rush on this for my sake - In actuality, the only reason I even used this code was because I was putting together a little demo for my son's preschool class about web development, and thought a color-changing ghost would be the thing to do - hence my need for converting hex colors (provided by 2 Umbraco properties) into HSL, so I could adjust the S & L values, and generate new hex codes for use in an SVG graphic. 

Anyway, my demo is finished, and I'm not using this in "production" anywhere - I just had to write my own helper because I didn't see the "Parse()" methods, and figured I'd give back to the project. :-)

**Comment by abjerner** [comment]
@hfloyd thanks - and appreciated 👍

I'll should be able to look at this tomorrow 😉

**Pull request merged**
